/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginBT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        alamatemail = new javax.swing.JLabel();
        AlamatEmail = new javax.swing.JTextField();
        katasandi = new javax.swing.JLabel();
        KataSandi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SignUpBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBT.setBackground(new java.awt.Color(255, 75, 58));
        LoginBT.setForeground(new java.awt.Color(255, 255, 255));
        LoginBT.setText("Login");
        LoginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Group 68.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Haii Ayo Jelajahi Kuliner Kampus");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Rectangle 3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -120, 350, 310));

        alamatemail.setText("Alamat Email");
        jPanel1.add(alamatemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 20));
        jPanel1.add(AlamatEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 190, 30));

        katasandi.setText("Kata Sandi");
        jPanel1.add(katasandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 20));
        jPanel1.add(KataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 190, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 75, 58));
        jLabel8.setText("Belum Punya Akun? ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 120, 30));

        SignUpBT.setText("SignUp");
        SignUpBT.setBorder(null);
        SignUpBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBTActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTActionPerformed
        // TODO add your handling code here:
       String alamatemail = AlamatEmail.getText();
       String katasandi = KataSandi.getText();
                                             
        try (Connection conn = Koneksi.konek()) {
        String query = "SELECT * FROM user WHERE alamat_email = ? AND kata_sandi = ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, alamatemail);
        pstmt.setString(2, katasandi);
        
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) { // Jika ada hasil, login berhasil
            new menu().setVisible(true); // Membuka form Kalkulator jika login sukses
            dispose();
        } else { // Jika tidak ada hasil, login gagal
            JOptionPane.showMessageDialog(null, "ID atau Password salah!", "Pesan Salah", JOptionPane.ERROR_MESSAGE);
            AlamatEmail.setText("");
            KataSandi.setText("");
            AlamatEmail.requestFocus();
        }
    } catch (SQLException | ClassNotFoundException e) {
        JOptionPane.showMessageDialog(null, "Gagal menghubungkan ke database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_LoginBTActionPerformed

    private void SignUpBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBTActionPerformed
        // TODO add your handling code here:
        Signup SignUpBT = new Signup(); // Pastikan SignUpMenu adalah kelas untuk layar SignUp Anda
        SignUpBT.setVisible(true);  // Tampilkan layar SignUp
        this.dispose();
    }//GEN-LAST:event_SignUpBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatEmail;
    private javax.swing.JTextField KataSandi;
    private javax.swing.JButton LoginBT;
    private javax.swing.JButton SignUpBT;
    private javax.swing.JLabel alamatemail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel katasandi;
    // End of variables declaration//GEN-END:variables
}
