/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author LENOVO
 */
public class Pembayaran extends javax.swing.JFrame {

    private int selectedRow;

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
        loadOrdersToTable();
    }

    private JTextField txtTotalHarga;
    private JTextField txtBayar;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        Pembayaran = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        pembayaran = new javax.swing.JComboBox<>();
        TotalHarga = new javax.swing.JLabel();
        totalHarga = new javax.swing.JTextField();
        Bayar = new javax.swing.JLabel();
        CetakTransaksiBT = new javax.swing.JButton();
        BayarBT = new javax.swing.JButton();
        bayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rincian = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ClearBT = new javax.swing.JButton();
        EditBT = new javax.swing.JButton();
        HapusBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel1.setBackground(new java.awt.Color(255, 255, 255));
        Jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Jpanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Tanggal.setText("Tanggal");
        Jpanel1.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        Pembayaran.setText("Pembayaran");
        Jpanel1.add(Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));
        Jpanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 150, -1));

        pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Qris", "Transfer Bank" }));
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        Jpanel1.add(pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 150, -1));

        TotalHarga.setText("Total Harga");
        TotalHarga.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TotalHargaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Jpanel1.add(TotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, -1, -1));

        totalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaActionPerformed(evt);
            }
        });
        Jpanel1.add(totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 160, 20));

        Bayar.setText("Bayar");
        Bayar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                BayarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Jpanel1.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, -1, -1));

        CetakTransaksiBT.setBackground(new java.awt.Color(242, 242, 242));
        CetakTransaksiBT.setText("Cetak Transaksi");
        CetakTransaksiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakTransaksiBTActionPerformed(evt);
            }
        });
        Jpanel1.add(CetakTransaksiBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, -1, -1));

        BayarBT.setBackground(new java.awt.Color(255, 75, 58));
        BayarBT.setForeground(new java.awt.Color(255, 255, 255));
        BayarBT.setText("Bayar");
        BayarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarBTActionPerformed(evt);
            }
        });
        Jpanel1.add(BayarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, -1, -1));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        Jpanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 160, 20));

        rincian.setBackground(new java.awt.Color(242, 242, 242));
        rincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu Dipesan", "Jumlah", "Harga"
            }
        ));
        rincian.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                rincianAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(rincian);

        Jpanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 97, 1010, 370));

        jPanel2.setBackground(new java.awt.Color(255, 75, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pembayaran");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jpanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 90));

        ClearBT.setBackground(new java.awt.Color(255, 75, 58));
        ClearBT.setForeground(new java.awt.Color(255, 255, 255));
        ClearBT.setText("Clear");
        ClearBT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ClearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTActionPerformed(evt);
            }
        });
        Jpanel1.add(ClearBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 70, 30));

        EditBT.setBackground(new java.awt.Color(255, 75, 58));
        EditBT.setForeground(new java.awt.Color(255, 255, 255));
        EditBT.setText("Edit");
        EditBT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EditBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBTActionPerformed(evt);
            }
        });
        Jpanel1.add(EditBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 70, 30));

        HapusBT.setBackground(new java.awt.Color(255, 75, 58));
        HapusBT.setForeground(new java.awt.Color(255, 255, 255));
        HapusBT.setText("Hapus");
        HapusBT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        HapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBTActionPerformed(evt);
            }
        });
        Jpanel1.add(HapusBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranActionPerformed

    private void totalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaActionPerformed

    private void CetakTransaksiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakTransaksiBTActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Transaksi dicetak!");
    }//GEN-LAST:event_CetakTransaksiBTActionPerformed

    private void BayarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarBTActionPerformed
        // TODO add your handling code here:
        try {
            if (txtTotalHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Total harga kosong. Silakan tambahkan item terlebih dahulu.");
            return;
        }
            double totalHarga = Double.parseDouble(txtTotalHarga.getText());
            double bayar = Double.parseDouble(txtBayar.getText());

            if (bayar >= totalHarga) {
                double kembalian = bayar - totalHarga;
                JOptionPane.showMessageDialog(this, "Pembayaran berhasil! Kembalian: " + kembalian);
            } else {
                JOptionPane.showMessageDialog(this, "Jumlah bayar kurang!");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid di kolom Bayar!");
        }
    }//GEN-LAST:event_BayarBTActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void ClearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTActionPerformed
        // TODO add your handling code here:
        txtTotalHarga.setText("");
        txtBayar.setText("");
        DefaultTableModel model = (DefaultTableModel) rincian.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_ClearBTActionPerformed

    private void EditBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBTActionPerformed
        // TODO add your handling code here:
        int selectedRow = rincian.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit.");
            return;
        }
        String newMenu = JOptionPane.showInputDialog(this, "Masukkan nama menu baru:");
        String newHarga = JOptionPane.showInputDialog(this, "Masukkan jumlah baru:");
        String newJumlah = JOptionPane.showInputDialog(this, "Masukkan harga baru:");
        rincian.setValueAt(newMenu, selectedRow, 0);
        rincian.setValueAt(newHarga, selectedRow, 1);
        rincian.setValueAt(newJumlah, selectedRow, 2);
    }//GEN-LAST:event_EditBTActionPerformed

    private void HapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBTActionPerformed
        // TODO add your handling code here:
        if (selectedRow != -1) { // Jika ada baris yang dipilih
            // Mendapatkan nilai dari kolom tertentu (misalnya ID)
            String menuDipilih = rincian.getValueAt(selectedRow, 0).toString(); // Kolom 0 sebagai contoh
            
            // Konfirmasi sebelum menghapus
            int confirm = JOptionPane.showConfirmDialog(null, 
                    "Apakah Anda yakin ingin menghapus data " + menuDipilih + "?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);
            
            
        }
    }//GEN-LAST:event_HapusBTActionPerformed

    private void TotalHargaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TotalHargaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaAncestorAdded

    private void BayarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_BayarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarAncestorAdded

    private void rincianAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rincianAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_rincianAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bayar;
    private javax.swing.JButton BayarBT;
    private javax.swing.JButton CetakTransaksiBT;
    private javax.swing.JButton ClearBT;
    private javax.swing.JButton EditBT;
    private javax.swing.JButton HapusBT;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JLabel Pembayaran;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel TotalHarga;
    private javax.swing.JTextField bayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pembayaran;
    private javax.swing.JTable rincian;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField totalHarga;
    // End of variables declaration//GEN-END:variables

    private void loadOrdersToTable() {
        
    // Dapatkan model tabel
    DefaultTableModel model = (DefaultTableModel) rincian.getModel();

    // Bersihkan tabel sebelum mengisi data baru
    model.setRowCount(0);

    // Ambil data dari database
    OrderRepository orderRepo = new OrderRepository();
    List<Object[]> orders = orderRepo.getOrders();

    // Isi tabel dengan data dari database
    for (Object[] order : orders) {
        model.addRow(order);
    }

    System.out.println("Data pesanan berhasil dimuat ke tabel.");
    }
 }